// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXm0kMvv5odpkkrHKRNZz2Cm6mvTx2uDg',
    appId: '1:514133180208:android:45009c17a5721198b2d2f5',
    messagingSenderId: '514133180208',
    projectId: 'ant-assistive-nav',
    storageBucket: 'ant-assistive-nav.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLONZsYeV6w0EjqxlIu635NZn5gkKzyo',
    appId: '1:514133180208:ios:29337911449bdc5cb2d2f5',
    messagingSenderId: '514133180208',
    projectId: 'ant-assistive-nav',
    storageBucket: 'ant-assistive-nav.firebasestorage.app',
    iosBundleId: 'com.ant.assistive.antApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKx3oyowZvOnBlhg_Ucondo1VtdazF1A',
    appId: '1:514133180208:web:21b1af9f8867af60b2d2f5',
    messagingSenderId: '514133180208',
    projectId: 'ant-assistive-nav',
    authDomain: 'ant-assistive-nav.firebaseapp.com',
    storageBucket: 'ant-assistive-nav.firebasestorage.app',
  );
}
